server:
  port: ${PORT:8081}

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslMode=REQUIRED&useSSL=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # Eureka disable - Render par direct URL use karenge
  cloud:
    discovery:
      enabled: false

eureka:
  client:
    enabled: false

jwt:
  secret: ${JWT_SECRET:qmsMicroservicesSecretKeyForJwtToken2024VeryLongSecretKey}
  expiration: 86400000
